services:
 deepcad:
   build: ./DeepCAD
   image: chriszengerle/aigen_deepcad:0.1
   container_name: deepcad
   volumes:
     - ./DeepCAD:/usr/app/src/DeepCAD

     # Cluster bindings
     - ../utils/models/DeepCAD:/usr/app/src/DeepCAD/proj_log
     - ../utils/data:/usr/app/src/DeepCAD/data

     # local Windows bindings (Christoph)
     # - C:/ArtificialIntelligence/DeepCAD/data:/usr/app/src/DeepCAD/data
     # - C:/ArtificialIntelligence/DeepCAD/proj_log:/usr/app/src/DeepCAD/proj_log

   # network_mode: "host"
   ports:
     - "5002:5002"
     - "8082:22" # SSH
     - "8083:6006" # Tensorboard
     - "8084:8888" # Jupyter

   # command: tail -F anything #to keep Container running
   ipc: host
   deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             device_ids: ["0"] # binds to GPU 0 and 1
             # count: all
             capabilities: [gpu]



 instantmesh:
   build: ./InstantMesh
   image: chriszengerle/aigen_instantmesh:0.1
   container_name: instantmesh
   volumes:
     - ./InstantMesh:/usr/app/src/InstantMesh

     # Cluster bindings
     - ../utils/data:/usr/app/src/instantMesh/data
     - ../instantmesh_ckpts:/usr/app/src/InstantMesh/ckpts
     # - ../utils/models/InstantMesh:/usr/app/src/InstantMesh/ckpts

   # network_mode: "host"
   ports:
     - "8085:22" # SSH
     - "8086:6006" # Tensorboard
     - "8087:8888" # Jupyter
     - "5001:5001" # Gradio

   # command: tail -F anything #to keep Container running
   ipc: host
   deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             device_ids: ["1"] # binds to GPU 0 and 1
             # count: all
             capabilities: [ gpu ]


 app:
    container_name: app
    build: ./App
    image: chriszengerle/aigen_app:0.1
    env_file: "AiGen_CAD.env"
    volumes:
      - ./App:/usr/app/src/App 
      - ../utils/data:/usr/app/src/App/data

    ports:
      - "8088:22" # SSH<
      - "7860:7860" # Gradio

    depends_on:
      - deepcad
      - instantmesh

    ipc: host
    # command: tail -F anything #to keep Container running
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # device_ids: ["1"] # binds to GPU 0 and 1
              count: all
              capabilities: [ gpu ]

