services:
  deepcad:
    build: ./DeepCAD
    image: chriszengerle/aigen_deepcad:0.1
    container_name: deepcad
    volumes:
      - ./DeepCAD:/usr/app/src/DeepCAD
      - ../utils/models/DeepCAD:/usr/app/src/DeepCAD/proj_log
      - ../utils/data:/usr/app/src/DeepCAD/data
    command: tail -F anything #to keep Container running
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0", "1"] # binds to GPU 0 and 1
              capabilities: [gpu]
