services:
 deepcad:
   build: 
    context: ./DeepCAD
    dockerfile: ./DeepCAD/Dockerfile
   image: chriszengerle/aigen_deepcad:0.1
   container_name: deepcad
   volumes:
     - ./DeepCAD:/usr/app/src/DeepCAD

     # Cluster bindings
     - ../utils/models/DeepCAD:/usr/app/src/DeepCAD/proj_log
     - ../utils/data:/usr/app/src/DeepCAD/data

     # local Windows bindings (Christoph)
     # - C:/ArtificialIntelligence/DeepCAD/data:/usr/app/src/DeepCAD/data
     # - C:/ArtificialIntelligence/DeepCAD/proj_log:/usr/app/src/DeepCAD/proj_log

   # network_mode: "host"
   ports:
     - "8082:22" # SSH
     - "8083:6006" # Tensorboard
     - "8084:8888" # Jupyter

   command: tail -F anything #to keep Container running
   ipc: host
   deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             # device_ids: ["0", "1"] # binds to GPU 0 and 1
             count: all
             capabilities: [gpu]



 instantmesh:
   build: ./InstantMesh
   image: chriszengerle/aigen_instantmesh:0.1
   container_name: instantmesh
   volumes:
     - ./InstantMesh:/usr/app/src/InstantMesh

     # Cluster bindings
     - ./utils/data:/usr/app/src/InstantMesh/data
     - ./utils/models/InstantMesh:/usr/app/src/InstantMesh/ckpts

   # network_mode: "host"
   ports:
     - "8085:22" # SSH
     - "8086:6006" # Tensorboard
     - "8087:8888" # Jupyter
     - "7860:7860" # Gradio

   command: tail -F anything #to keep Container running
   ipc: host
   deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             # device_ids: ["0", "1"] # binds to GPU 0 and 1
             count: all
             capabilities: [ gpu ]



  # pipeline:
  #   container_name: pipeline
  #   build: .
  #   volumes:
  #     - ./InstantMesh:/usr/app/src/InstantMesh
  #     - ./DeepCAD:/usr/app/src/DeepCAD

  #     # Cluster bindings
  #     - ./utils/data:/usr/app/src/data

  #     # local Windows bindings (Christoph)
  #     # - C:/ArtificialIntelligence/DeepCAD/data:/usr/app/src/DeepCAD/data
  #     # - C:/ArtificialIntelligence/DeepCAD/proj_log:/usr/app/src/DeepCAD/proj_log

  #   # network_mode: "host"
  #   ports:
  #     - "8082:22" # SSH
  #     - "8083:6006" # Tensorboard
  #     - "8084:8888" # Jupyter
  #     - "7860:7860"

  #   command: tail -F anything #to keep Container running
  #   ipc: host
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             # device_ids: ["0", "1"] # binds to GPU 0 and 1
  #             count: all
  #             capabilities: [ gpu ]

