services:
  deepcad:
    build: ./DeepCAD
    image: chriszengerle/aigen_deepcad:0.1
    container_name: deepcad
    volumes:
      - ./DeepCAD:/usr/app/src/DeepCAD
      
      # Cluster bindings
      - ../utils/models/DeepCAD:/usr/app/src/DeepCAD/proj_log
      - ../utils/data:/usr/app/src/DeepCAD/data
      
      # local Windows bindings (Christoph)
      # - C:/ArtificialIntelligence/DeepCAD/data:/usr/app/src/DeepCAD/data
      # - C:/ArtificialIntelligence/DeepCAD/proj_log:/usr/app/src/DeepCAD/proj_log
    command: tail -F anything #to keep Container running
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # device_ids: ["0", "1"] # binds to GPU 0 and 1
              count: all
              capabilities: [gpu]
