services:
  deepcad:
    build: ./DeepCAD
    image: chriszengerle/aigen_deepcad:0.1
    container_name: deepcad
    env_file: "AiGen_CAD.env"
    volumes:
      - ./DeepCAD:/usr/app/src/DeepCAD

      # Cluster bindings
      - ../utils/models/DeepCAD:/usr/app/src/DeepCAD/proj_log
      - ../utils/data:/usr/app/src/DeepCAD/data
      - ../utils/results:/usr/app/src/DeepCAD/results

    ports:
      - "8082:22" # SSH
      - "8083:6006" # Tensorboard
      - "8092:8092" # Flask

    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  instantmesh:
    build: ./InstantMesh
    image: chriszengerle/aigen_instantmesh:0.1
    container_name: instantmesh
    env_file: "AiGen_CAD.env"
    volumes:
      - ./InstantMesh:/usr/app/src/InstantMesh

      # Cluster bindings
      - ../utils/data:/usr/app/src/InstantMesh/data
      - ../utils/models/InstantMesh:/usr/app/src/InstantMesh/ckpts
      - ../utils/results:/usr/app/src/InstantMesh/results

    ports:
      - "8085:22" # SSH
      - "8086:6006" # Tensorboard
      - "8091:8091" # Flask

    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"] # binds to GPU 0 and 1
              capabilities: [gpu]
  app:
    build: ./App
    image: chriszengerle/aigen_app:0.1
    container_name: app
    depends_on:
      - deepcad
      - instantmesh
    env_file: "AiGen_CAD.env"
    volumes:
      - ./App:/usr/app/src/App

      # Cluster bindings
      - ../utils/data:/usr/app/src/App/data
      - ../utils/results:/usr/app/src/App/results

    ports:
      - "8088:22" # SSH
      - "7860:7860" # Gradio

    ipc: host
    command: tail -F anything #to keep Container running
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
